[package]
name = "static-trignometry-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0.20.10"
num-traits = "0.2.19"
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = "2.0.89"
